Section "ServerFlags"
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
    Option "DontVTSwitch" "true"
    Option "AutoAddDevices" "true"
    Option "AutoEnableDevices" "true"
    Option "AllowMouseOpenFail" "true"
    Option "XkbDisable" "false"
EndSection
Section "InputClass"
    Identifier "gptokeyb fake keyboard"
    MatchProduct "Fake Keyboard"
    MatchDevicePath "/dev/input/event*"
    Option "CorePointer" "true"
    Driver "evdev"
EndSection
Section "Files"
    ModulePath "/mnt/SDCARD/Roms/PORTS/you-and-me-and-her/totono-runtime/tsps-modules/drivers"
    ModulePath "/mnt/SDCARD/Roms/PORTS/you-and-me-and-her/totono-runtime/tsps-modules/input"
    ModulePath "/mnt/UDISK/xorg/usr/lib/xorg/modules"
EndSection
Section "Monitor"
    Identifier "AWPanel"
    Modeline "1280x720" 74.25 1280 1390 1430 1650 720 725 730 750
    Option "PreferredMode" "1280x720"
    Option "Enable" "true"
EndSection
Section "Device"
    Identifier "FB"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
    Option "ShadowFB" "true"
    Option "TSPSRotateCopy" "CW"
EndSection
Section "Screen"
    Identifier "Screen0"
    Device "FB"
    Monitor "AWPanel"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1280x720"
    EndSubSection
EndSection
Section "ServerLayout"
    Identifier "Layout0"
    Screen 0 "Screen0"
EndSection
