#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>
#include <vulkan/vulkan.h>
static int has(const VkExtensionProperties*e,uint32_t n,const char*s){for(uint32_t i=0;i<n;i++)if(!strcmp(e[i].extensionName,s))return 1;return 0;}
int main(void){void*l=dlopen("libvulkan.so.1",RTLD_NOW|RTLD_LOCAL);if(!l){fprintf(stderr,"FAIL dlopen: %s\n",dlerror());return 2;}PFN_vkGetInstanceProcAddr g=(PFN_vkGetInstanceProcAddr)dlsym(l,"vkGetInstanceProcAddr");if(!g)return 2;PFN_vkEnumerateInstanceVersion ev=(PFN_vkEnumerateInstanceVersion)g(0,"vkEnumerateInstanceVersion");uint32_t lv=VK_API_VERSION_1_0;if(ev)ev(&lv);printf("loader_api=%u.%u.%u\n",VK_API_VERSION_MAJOR(lv),VK_API_VERSION_MINOR(lv),VK_API_VERSION_PATCH(lv));
 VkApplicationInfo ai={.sType=VK_STRUCTURE_TYPE_APPLICATION_INFO,.pApplicationName="animalwell-vkprobe",.apiVersion=lv};VkInstanceCreateInfo ci={.sType=VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,.pApplicationInfo=&ai};PFN_vkCreateInstance cr=(PFN_vkCreateInstance)g(0,"vkCreateInstance");VkInstance in=0;VkResult vr=cr(&ci,0,&in);if(vr!=VK_SUCCESS){printf("FAIL vkCreateInstance=%d\n",vr);return 3;}
 PFN_vkEnumeratePhysicalDevices ep=(PFN_vkEnumeratePhysicalDevices)g(in,"vkEnumeratePhysicalDevices");PFN_vkGetPhysicalDeviceProperties gp=(PFN_vkGetPhysicalDeviceProperties)g(in,"vkGetPhysicalDeviceProperties");PFN_vkEnumerateDeviceExtensionProperties ee=(PFN_vkEnumerateDeviceExtensionProperties)g(in,"vkEnumerateDeviceExtensionProperties");PFN_vkGetPhysicalDeviceFeatures2 gf=(PFN_vkGetPhysicalDeviceFeatures2)g(in,"vkGetPhysicalDeviceFeatures2");PFN_vkGetPhysicalDeviceProperties2 gp2=(PFN_vkGetPhysicalDeviceProperties2)g(in,"vkGetPhysicalDeviceProperties2");PFN_vkDestroyInstance di=(PFN_vkDestroyInstance)g(in,"vkDestroyInstance");uint32_t nd=0;ep(in,&nd,0);if(!nd){puts("FAIL no Vulkan device");return 4;}VkPhysicalDevice*ds=calloc(nd,sizeof(*ds));ep(in,&nd,ds);
 const char*r26[]={"VK_EXT_descriptor_indexing","VK_KHR_timeline_semaphore","VK_KHR_create_renderpass2","VK_KHR_sampler_mirror_clamp_to_edge","VK_EXT_robustness2","VK_KHR_separate_depth_stencil_layouts","VK_KHR_bind_memory2","VK_KHR_copy_commands2"};const char*r30[]={"VK_EXT_robustness2","VK_KHR_push_descriptor"};
 for(uint32_t x=0;x<nd;x++){VkPhysicalDeviceProperties p;gp(ds[x],&p);printf("device[%u].name=%s\ndevice[%u].api=%u.%u.%u\n",x,p.deviceName,x,VK_API_VERSION_MAJOR(p.apiVersion),VK_API_VERSION_MINOR(p.apiVersion),VK_API_VERSION_PATCH(p.apiVersion));uint32_t ne=0;ee(ds[x],0,&ne,0);VkExtensionProperties*es=calloc(ne,sizeof(*es));ee(ds[x],0,&ne,es);int p26=(VK_API_VERSION_MAJOR(p.apiVersion)>1||VK_API_VERSION_MINOR(p.apiVersion)>=1),p30=(VK_API_VERSION_MAJOR(p.apiVersion)>1||VK_API_VERSION_MINOR(p.apiVersion)>=3);for(unsigned i=0;i<sizeof(r26)/sizeof(*r26);i++){int h=has(es,ne,r26[i]);printf("ext.%s=%s\n",r26[i],h?"yes":"no");if(!h)p26=0;}for(unsigned i=0;i<sizeof(r30)/sizeof(*r30);i++){int h=has(es,ne,r30[i]);printf("ext.%s=%s\n",r30[i],h?"yes":"no");if(!h)p30=0;}
 VkPhysicalDeviceDescriptorIndexingFeatures f={.sType=VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES};VkPhysicalDeviceFeatures2 f2={.sType=VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2,.pNext=&f};if(gf)gf(ds[x],&f2);printf("descriptor.runtimeArray=%u\ndescriptor.partiallyBound=%u\ndescriptor.sampledUpdateAfterBind=%u\n",f.runtimeDescriptorArray,f.descriptorBindingPartiallyBound,f.descriptorBindingSampledImageUpdateAfterBind);if(!f.runtimeDescriptorArray||!f.descriptorBindingPartiallyBound||!f.descriptorBindingSampledImageUpdateAfterBind)p26=p30=0;
 VkPhysicalDeviceDescriptorIndexingProperties ip={.sType=VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES};VkPhysicalDeviceProperties2 pp={.sType=VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2,.pNext=&ip};if(gp2)gp2(ds[x],&pp);printf("limit.updateAfterBindSampledImages=%u\n",ip.maxDescriptorSetUpdateAfterBindSampledImages);if(ip.maxDescriptorSetUpdateAfterBindSampledImages<1000000U)p26=p30=0;printf("vkd3d-proton-2.6-precheck=%s\nvkd3d-proton-3.0.1-precheck=%s\n",p26?"PASS":"FAIL",p30?"PASS":"FAIL");free(es);}free(ds);di(in,0);dlclose(l);return 0;}
